//[[!! include('device', 'LC4032ZE_csBGA64') !! 77 ]]
//[[ ################# !! GENERATED CODE -- DO NOT MODIFY !! ################# ]]
const std = @import("std");
const device_pins = @import("device_pins.zig");

pub const pins = buildPins();

fn buildPins() [64]device_pins.PinInfo {
    var b = device_pins.PinInfoBuilder {};
    return .{
        b.goe("B4", 0, 0, 0, 0),
        b.io("B3", 0, 0, 1),
        b.io("C2", 0, 0, 6),
        b.io("C1", 0, 0, 7),
        b.misc("C3", .no_connect),
        b.io("A3", 0, 0, 2),
        b.io("A2", 0, 0, 3),
        b.io("A1", 0, 0, 4),
        b.io("B1", 0, 0, 5),
        b.io("H4", 0, 0, 15),
        b.misc("E2", .no_connect),
        b.io("F1", 0, 0, 11),
        b.io("D3", 0, 0, 10),
        b.io("E1", 0, 0, 9),
        b.misc("D2", .no_connect),
        b.io("D1", 0, 0, 8),
        b.misc("F3", .no_connect),
        b.io("G3", 0, 0, 14),
        b.io("H3", 0, 0, 13),
        b.misc("H2", .no_connect),
        b.io("G2", 0, 0, 12),
        b.misc("F2", .no_connect),
        b.misc("G1", .no_connect),
        b.io("F5", 1, 1, 0),
        b.io("G5", 1, 1, 1),
        b.io("F7", 1, 1, 6),
        b.io("G8", 1, 1, 7),
        b.misc("F8", .no_connect),
        b.io("G6", 1, 1, 2),
        b.io("H6", 1, 1, 3),
        b.io("F6", 1, 1, 4),
        b.misc("H7", .no_connect),
        b.io("G7", 1, 1, 5),
        b.clk("C4", 0, 0, 0),
        b.clk("G4", 0, 0, 1),
        b.clk("H5", 1, 1, 2),
        b.clk("A4", 1, 1, 3),
        b.goe("B5", 1, 1, 15, 1),
        b.misc("C5", .no_connect),
        b.misc("D8", .no_connect),
        b.io("D7", 1, 1, 10),
        b.io("E6", 1, 1, 9),
        b.misc("E7", .no_connect),
        b.io("E8", 1, 1, 8),
        b.misc("A5", .no_connect),
        b.io("B6", 1, 1, 14),
        b.io("A6", 1, 1, 13),
        b.misc("B7", .no_connect),
        b.misc("A7", .no_connect),
        b.io("A8", 1, 1, 12),
        b.misc("C8", .no_connect),
        b.io("C7", 1, 1, 11),
        b.misc("D4", .gnd),
        b.misc("E5", .gnd),
        b.misc("H1", .tck),
        b.misc("B2", .tdi),
        b.misc("B8", .tdo),
        b.misc("H8", .tms),
        b.misc("D5", .vcc_core),
        b.misc("E4", .vcc_core),
        b.misc("E3", .vcco_bank_0),
        b.misc("F4", .no_connect),
        b.misc("C6", .no_connect),
        b.misc("D6", .vcco_bank_1),
    };
}
//[[ ######################### END OF GENERATED CODE ######################### ]]
