on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: zig-master
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: zig-master
      - uses: mlugg/setup-zig@v2
        with:
          version: master
          mirror: 'https://zig.bcr.ist/'
      - run: zig build
      - run: zig build -Dtarget=x86_64-windows
        working-directory: ./generate/
